# Generated by Django 2.1.7 on 2020-09-27 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'others')], default=None, max_length=20)),
                ('date_of_birth', models.DateField()),
                ('Highest_Education', models.CharField(choices=[('uneducated', 'uneducated'), ('5th Class', '5th Class'), ('8th Class', '8th Class'), ('10th Class', '10th Class'), ('12th Class', '12th Class'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation'), ('Doctorate', 'Doctorate')], max_length=20)),
                ('Country', models.CharField(choices=[('India', 'India'), ('Others', 'Others')], max_length=20)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follower', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='User_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
