# Generated by Django 2.1.7 on 2020-09-27 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile_otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=13)),
                ('OTP', models.CharField(max_length=4)),
                ('Time', models.DateTimeField(default=datetime.datetime(2020, 9, 27, 17, 27, 19, 135757))),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'others')], max_length=20),
        ),
    ]
