# Generated by Django 2.1.7 on 2020-09-27 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200927_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_otp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 17, 35, 18, 541912)),
        ),
    ]
