# Generated by Django 2.1.7 on 2020-09-27 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20200927_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 1, 45, 2, 531977)),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='constituency',
            field=models.CharField(choices=[('PUROLA', 'Purola'), ('YAMUNOTRI', 'Yamunotri'), ('GANGOTRI', 'Gangotri'), ('BADRINATH', 'Badrinath'), ('THARALI', 'Tharali'), ('KARANPRAYAG', 'Karanprayag'), ('KEDARNATH', 'Kedarnath'), ('RUDRAPRAYAG', 'Rudraprayag'), ('GHANSALI', 'Ghansali'), ('DEOPRAYAG', 'Deoprayag'), ('NARENDRANAGAR', 'Narendranagar'), ('PRATAP', 'Pratap'), ('TEHRI', 'Tehri'), ('DHANOLTI', 'Dhanolti'), ('CHAKRATA', 'Chakrata'), ('VIKASNAGAR', 'Vikasnagar'), ('SAHASPUR', 'Sahaspur'), ('DHARAMPUR', 'Dharampur'), ('RAIPUR', 'Raipur'), ('RAJPUR', 'Rajpur'), ('DEHRADUN', 'Dehradun'), ('MUSSOORIE', 'Mussoorie'), ('DOIWALA', 'Doiwala'), ('RISHIKESH', 'Rishikesh'), ('HARIDWAR', 'Haridwar'), ('B.H.E.L', 'B.H.E.L'), ('JWALAPUR', 'Jwalapur'), ('BHAGWANPUR', 'Bhagwanpur'), ('JHABRERA', 'Jhabrera'), ('PIRANKALIYAR', 'Pirankaliyar'), ('ROORKEE', 'Roorkee'), ('KHANPUR', 'Khanpur'), ('MANGLORE', 'Manglore'), ('LAKSAR', 'Laksar'), ('HARIDWAR', 'Haridwar'), ('YAMKESHWAR', 'Yamkeshwar'), ('PAURI', 'Pauri'), ('SRINAGAR', 'Srinagar'), ('CHAUBATTAKHAL', 'Chaubattakhal'), ('LANSDOWNE', 'Lansdowne'), ('KOTDWAR', 'Kotdwar'), ('DHARCHULA', 'Dharchula'), ('DIDIHAT', 'Didihat'), ('PITHORAGARH', 'Pithoragarh'), ('GANGOLIHAT', 'Gangolihat'), ('KAPKOTE', 'Kapkote'), ('BAGESHWAR', 'Bageshwar'), ('DWARAHAT', 'Dwarahat'), ('SALT', 'Salt'), ('RANIKHET', 'Ranikhet'), ('SOMESHWAR', 'Someshwar'), ('ALMORA', 'Almora'), ('JAGESHWAR', 'Jageshwar'), ('LOHAGHAT', 'Lohaghat'), ('CHAMPAWAT', 'Champawat'), ('LALKUWA', 'LalKuwa'), ('BHIMTAAL', 'Bhimtaal'), ('NAINITAL', 'Nainital'), ('HALDWANI', 'Haldwani'), ('KALABHUNGI', 'Kalabhungi'), ('RAMNAGAR', 'Ramnagar'), ('JASPUR', 'Jaspur'), ('KASHIPUR', 'Kashipur'), ('BAJPUR', 'Bajpur'), ('GADARPUR', 'Gadarpur'), ('RUDRAPUR', 'Rudrapur'), ('KICHHA', 'Kichha'), ('SITARGANJ', 'Sitarganj'), ('NANAK', 'Nanak'), ('KHATIMA', 'Khatima')], max_length=30),
        ),
    ]
