# Generated by Django 2.1.7 on 2020-09-27 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20200928_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 3, 37, 57, 604962)),
        ),
        migrations.AlterField(
            model_name='mobileotp',
            name='mobile_number',
            field=models.CharField(max_length=13),
        ),
    ]
