# Generated by Django 2.1.7 on 2020-09-29 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20200928_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='web_pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=10)),
                ('page_name', models.CharField(max_length=30, unique=True)),
                ('page_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='mobileotp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 23, 45, 26, 450865)),
        ),
    ]
