# Generated by Django 2.1.7 on 2020-09-29 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20200929_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 0, 0, 41, 39519)),
        ),
    ]
