# Generated by Django 2.1.7 on 2020-09-29 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_auto_20200930_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 3, 10, 41, 785253)),
        ),
        migrations.AlterField(
            model_name='web_pages',
            name='page_text',
            field=models.CharField(max_length=8000),
        ),
    ]
