# Generated by Django 2.1.7 on 2020-09-29 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_auto_20200930_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='City',
            new_name='District',
        ),
        migrations.AlterField(
            model_name='mobileotp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 3, 58, 3, 845778)),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Country',
            field=models.CharField(max_length=20),
        ),
    ]
