# Generated by Django 2.1.7 on 2020-10-01 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20200930_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 22, 56, 3, 367834)),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='follower',
            field=models.CharField(max_length=13),
        ),
    ]
