# Generated by Django 2.1.7 on 2020-10-01 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20201001_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='Number_of_follower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mobileotp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 23, 28, 23, 299322)),
        ),
    ]
