# Generated by Django 2.1.7 on 2020-10-02 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20201001_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 14, 33, 32, 182854)),
        ),
    ]
