# Generated by Django 2.1.7 on 2020-10-02 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20201002_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 14, 33, 55, 751575)),
        ),
    ]
