# Generated by Django 2.1.7 on 2020-10-02 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20201002_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 11, 43, 8, 781780, tzinfo=utc)),
        ),
    ]
