# Generated by Django 2.1.7 on 2020-10-02 11:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20201002_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 11, 44, 9, 85037, tzinfo=utc)),
        ),
    ]
